#!/bin/sh
# postinst script for lazyfier

SHORTCUT_NAME=$HOME/.config/autostart/paythebillreminder.desktop

echo "[Desktop Entry]" > $SHORTCUT_NAME
echo "Encoding=UTF-8" >> $SHORTCUT_NAME
echo "Type=Application" >> $SHORTCUT_NAME
echo "Name=Pay_The_Bills_Reminder" >> $SHORTCUT_NAME
echo "Comment='Reminder to pay the monthly bills'" >> $SHORTCUT_NAME
echo "Exec=/opt/paythebill/paythebillsreminder silent" >> $SHORTCUT_NAME
echo "StartupNotify=false" >> $SHORTCUT_NAME
echo "Terminal=false" >> $SHORTCUT_NAME
echo "Path=/opt/paythebill/" >> $SHORTCUT_NAME

exit 0
